Выполнено домашнее задание 4
JuliaZorina/CSharpEducation pull request #1
Opened 2024-09-16 19:40 UTC by JuliaZorina

Заходит в бар для вампиров богатый вампир-аристократ, и говорит:
-Мне пожалуйста кровь девственницы, четвертую группу.
Выпивает и уходит.
Заходит вампир среднего достатка:
-Мне кровь первой группы.
Выпивает и уходит.
Заходит бомж-вампир:
-Мне пожалуйста стакан кипятка.
Ему наливают, после чего он достает тампон со словами:
-Чайком побалуемся!

2024-09-18 16:51 UTC, Dezodemius requested changes

2024-09-18 16:51 UTC, Dezodemius commented on Task4/Task4/Employee.cs
> +    /// <summary>
Нужно пустой строкой отделить регион от хранящегося внутри кода

2024-09-18 16:51 UTC, Dezodemius commented on Task4/Task4/Employee.cs
> +    /// <summary>
Разделить члены пустой строкой нужно

2024-09-18 16:51 UTC, Dezodemius commented on Task4/Task4/Employee.cs
> +  public abstract class Employee
Нужно задокументировать

2024-09-18 16:51 UTC, Dezodemius commented on Task4/Task4/Employee.cs
> +    #region Конструкторы
Регион с конструкторами должен быть в самом низу по соглашению

2024-09-18 16:51 UTC, Dezodemius commented on Task4/Task4/Employee.cs
> +    protected Employee(string name, decimal baseSalary)
Документация нужна

2024-09-18 16:51 UTC, Dezodemius commented on Task4/Task4/EmployeeManager.cs
> +  public class EmployeeManager<T> : IEmployeeManager<T>
Документация

2024-09-18 16:51 UTC, Dezodemius commented on Task4/Task4/IEmployeeManager.cs
> +  public interface IEmployeeManager<T>
Документация

2024-09-18 16:51 UTC, Dezodemius commented on Task4/Task4/PartTimeEmployee.cs
> +  public class PartTimeEmployee : Employee
Документация

2024-09-18 16:51 UTC, Dezodemius commented on Task4/Task4/PartTimeEmployee.cs
> +      return this.BaseSalary* this.WorkingHours;
`return this.BaseSalary * this.WorkingHours`

Нужен пробел перед `*`

2024-09-20 11:49 UTC, JuliaZorina commented on Task4/Task4/Employee.cs
> +    /// <summary>
Исправила

2024-09-20 11:49 UTC, JuliaZorina commented on Task4/Task4/Employee.cs
> +    /// <summary>
Исправила

2024-09-20 11:49 UTC, JuliaZorina commented on Task4/Task4/Employee.cs
> +  public abstract class Employee
Задокументировала

2024-09-20 11:50 UTC, JuliaZorina commented on Task4/Task4/Employee.cs
> +    #region Конструкторы
Перенесла все конструкторы самый низ

2024-09-20 11:50 UTC, JuliaZorina commented on Task4/Task4/Employee.cs
> +    protected Employee(string name, decimal baseSalary)
Задокументировала

2024-09-20 11:50 UTC, JuliaZorina commented on Task4/Task4/EmployeeManager.cs
> +  public class EmployeeManager<T> : IEmployeeManager<T>
Задокументировала

2024-09-20 11:50 UTC, Dezodemius approved these changes

2024-09-20 11:50 UTC, JuliaZorina commented on Task4/Task4/IEmployeeManager.cs
> +  public interface IEmployeeManager<T>
Задокументировала

2024-09-20 11:50 UTC, JuliaZorina commented on Task4/Task4/PartTimeEmployee.cs
> +  public class PartTimeEmployee : Employee
Задокументировала

2024-09-20 11:50 UTC, JuliaZorina commented on Task4/Task4/PartTimeEmployee.cs
> +      return this.BaseSalary* this.WorkingHours;
Поставила пробелы

2024-09-20 11:54 UTC, merged